[2022-11-02 15:14:24,540] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: tutorial_request.bronze_senators scheduled__2022-11-01T00:00:00+00:00 [queued]>
[2022-11-02 15:14:24,548] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: tutorial_request.bronze_senators scheduled__2022-11-01T00:00:00+00:00 [queued]>
[2022-11-02 15:14:24,549] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-11-02 15:14:24,551] {taskinstance.py:1357} INFO - Starting attempt 2 of 3
[2022-11-02 15:14:24,552] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-11-02 15:14:24,562] {taskinstance.py:1377} INFO - Executing <Task(HttpSensor): bronze_senators> on 2022-11-01 00:00:00+00:00
[2022-11-02 15:14:24,567] {standard_task_runner.py:52} INFO - Started process 315 to run task
[2022-11-02 15:14:24,571] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'tutorial_request', 'bronze_senators', 'scheduled__2022-11-01T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/hello.py', '--cfg-path', '/tmp/tmpayewv6jv', '--error-file', '/tmp/tmpbohnil_u']
[2022-11-02 15:14:24,573] {standard_task_runner.py:80} INFO - Job 4: Subtask bronze_senators
[2022-11-02 15:14:24,630] {task_command.py:370} INFO - Running <TaskInstance: tutorial_request.bronze_senators scheduled__2022-11-01T00:00:00+00:00 [running]> on host f1a7bb9214cc
[2022-11-02 15:14:24,687] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@example.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=tutorial_request
AIRFLOW_CTX_TASK_ID=bronze_senators
AIRFLOW_CTX_EXECUTION_DATE=2022-11-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-01T00:00:00+00:00
[2022-11-02 15:14:24,689] {http.py:97} INFO - Poking: /extract/senators
[2022-11-02 15:14:24,701] {base.py:68} INFO - Using connection ID 'request_lakehouse' for task execution.
[2022-11-02 15:14:24,705] {http.py:129} INFO - Sending 'GET' to url: http://host.docker.internal:5000/extract/senators
[2022-11-02 15:14:24,738] {http.py:142} ERROR - HTTP error: Forbidden
[2022-11-02 15:14:24,739] {http.py:143} ERROR - 
[2022-11-02 15:14:24,760] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/http/hooks/http.py", line 140, in check_response
    response.raise_for_status()
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: http://host.docker.internal:5000/extract/senators

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/sensors/base.py", line 277, in execute
    poke_return = self.poke(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/http/sensors/http.py", line 112, in poke
    raise exc
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/http/sensors/http.py", line 103, in poke
    extra_options=self.extra_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/http/hooks/http.py", line 130, in run
    return self.run_and_check(session, prepped_request, extra_options)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/http/hooks/http.py", line 183, in run_and_check
    self.check_response(response)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/http/hooks/http.py", line 144, in check_response
    raise AirflowException(str(response.status_code) + ":" + response.reason)
airflow.exceptions.AirflowException: 403:Forbidden
[2022-11-02 15:14:24,767] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=tutorial_request, task_id=bronze_senators, execution_date=20221101T000000, start_date=20221102T151424, end_date=20221102T151424
[2022-11-02 15:14:24,777] {standard_task_runner.py:97} ERROR - Failed to execute job 4 for task bronze_senators (403:Forbidden; 315)
[2022-11-02 15:14:24,826] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-11-02 15:14:24,861] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
