[2022-11-02 15:09:44,054] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: tutorial_request.bronze_senators scheduled__2022-11-01T00:00:00+00:00 [queued]>
[2022-11-02 15:09:44,063] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: tutorial_request.bronze_senators scheduled__2022-11-01T00:00:00+00:00 [queued]>
[2022-11-02 15:09:44,066] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-11-02 15:09:44,067] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-11-02 15:09:44,068] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-11-02 15:09:44,083] {taskinstance.py:1377} INFO - Executing <Task(HttpSensor): bronze_senators> on 2022-11-01 00:00:00+00:00
[2022-11-02 15:09:44,088] {standard_task_runner.py:52} INFO - Started process 88 to run task
[2022-11-02 15:09:44,092] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'tutorial_request', 'bronze_senators', 'scheduled__2022-11-01T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/hello.py', '--cfg-path', '/tmp/tmpsli_mo6p', '--error-file', '/tmp/tmplxzs30k_']
[2022-11-02 15:09:44,093] {standard_task_runner.py:80} INFO - Job 3: Subtask bronze_senators
[2022-11-02 15:09:44,149] {task_command.py:370} INFO - Running <TaskInstance: tutorial_request.bronze_senators scheduled__2022-11-01T00:00:00+00:00 [running]> on host f1a7bb9214cc
[2022-11-02 15:09:44,206] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@example.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=tutorial_request
AIRFLOW_CTX_TASK_ID=bronze_senators
AIRFLOW_CTX_EXECUTION_DATE=2022-11-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-01T00:00:00+00:00
[2022-11-02 15:09:44,208] {http.py:97} INFO - Poking: /extract/senators
[2022-11-02 15:09:44,230] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/sensors/base.py", line 277, in execute
    poke_return = self.poke(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/http/sensors/http.py", line 112, in poke
    raise exc
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/http/sensors/http.py", line 103, in poke
    extra_options=self.extra_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/http/hooks/http.py", line 114, in run
    session = self.get_conn(headers)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/http/hooks/http.py", line 68, in get_conn
    conn = self.get_connection(self.http_conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/base.py", line 67, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 430, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `request_lakehouse` isn't defined
[2022-11-02 15:09:44,235] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=tutorial_request, task_id=bronze_senators, execution_date=20221101T000000, start_date=20221102T150944, end_date=20221102T150944
[2022-11-02 15:09:44,243] {standard_task_runner.py:97} ERROR - Failed to execute job 3 for task bronze_senators (The conn_id `request_lakehouse` isn't defined; 88)
[2022-11-02 15:09:44,266] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-11-02 15:09:44,308] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
