[2022-06-14 22:24:22,055] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: tutorial_request.sample-task manual__2022-06-14T22:24:19.928051+00:00 [queued]>
[2022-06-14 22:24:22,062] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: tutorial_request.sample-task manual__2022-06-14T22:24:19.928051+00:00 [queued]>
[2022-06-14 22:24:22,062] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-14 22:24:22,063] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-06-14 22:24:22,064] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-14 22:24:22,079] {taskinstance.py:1377} INFO - Executing <Task(SenatorsOperator): sample-task> on 2022-06-14 22:24:19.928051+00:00
[2022-06-14 22:24:22,084] {standard_task_runner.py:52} INFO - Started process 7490 to run task
[2022-06-14 22:24:22,088] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'tutorial_request', 'sample-task', 'manual__2022-06-14T22:24:19.928051+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/hello.py', '--cfg-path', '/tmp/tmpuwuzzj8t', '--error-file', '/tmp/tmprgbnfeb5']
[2022-06-14 22:24:22,090] {standard_task_runner.py:80} INFO - Job 30: Subtask sample-task
[2022-06-14 22:24:22,160] {task_command.py:370} INFO - Running <TaskInstance: tutorial_request.sample-task manual__2022-06-14T22:24:19.928051+00:00 [running]> on host c19de67e094a
[2022-06-14 22:24:22,217] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@example.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=tutorial_request
AIRFLOW_CTX_TASK_ID=sample-task
AIRFLOW_CTX_EXECUTION_DATE=2022-06-14T22:24:19.928051+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-14T22:24:19.928051+00:00
[2022-06-14 22:24:23,117] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/dags/operators/request/senators.py", line 27, in execute
    os.chdir('airflow/dags/operators/request')
FileNotFoundError: [Errno 2] No such file or directory: 'airflow/dags/operators/request'
[2022-06-14 22:24:23,138] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=tutorial_request, task_id=sample-task, execution_date=20220614T222419, start_date=20220614T222422, end_date=20220614T222423
[2022-06-14 22:24:23,157] {standard_task_runner.py:97} ERROR - Failed to execute job 30 for task sample-task ([Errno 2] No such file or directory: 'airflow/dags/operators/request'; 7490)
[2022-06-14 22:24:23,180] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-06-14 22:24:23,206] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
