[2022-06-20 23:25:11,060] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: tutorial_request.ola manual__2022-06-20T23:25:07.630792+00:00 [queued]>
[2022-06-20 23:25:11,066] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: tutorial_request.ola manual__2022-06-20T23:25:07.630792+00:00 [queued]>
[2022-06-20 23:25:11,067] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-20 23:25:11,068] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-06-20 23:25:11,069] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-20 23:25:11,078] {taskinstance.py:1377} INFO - Executing <Task(Ola): ola> on 2022-06-20 23:25:07.630792+00:00
[2022-06-20 23:25:11,085] {standard_task_runner.py:52} INFO - Started process 84 to run task
[2022-06-20 23:25:11,088] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'tutorial_request', 'ola', 'manual__2022-06-20T23:25:07.630792+00:00', '--job-id', '100', '--raw', '--subdir', 'DAGS_FOLDER/hello.py', '--cfg-path', '/tmp/tmphtdzf9k8', '--error-file', '/tmp/tmpfi3s7287']
[2022-06-20 23:25:11,106] {standard_task_runner.py:80} INFO - Job 100: Subtask ola
[2022-06-20 23:25:11,173] {task_command.py:370} INFO - Running <TaskInstance: tutorial_request.ola manual__2022-06-20T23:25:07.630792+00:00 [running]> on host e1cc88e9e73c
[2022-06-20 23:25:11,230] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@example.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=tutorial_request
AIRFLOW_CTX_TASK_ID=ola
AIRFLOW_CTX_EXECUTION_DATE=2022-06-20T23:25:07.630792+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-20T23:25:07.630792+00:00
[2022-06-20 23:25:11,266] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/dags/operators/silver/silver.py", line 11, in execute
    spark = SparkSession.builder.master("local[*]").getOrCreate()
  File "/home/airflow/.local/lib/python3.7/site-packages/pyspark/sql/session.py", line 269, in getOrCreate
    sc = SparkContext.getOrCreate(sparkConf)
  File "/home/airflow/.local/lib/python3.7/site-packages/pyspark/context.py", line 483, in getOrCreate
    SparkContext(conf=conf or SparkConf())
  File "/home/airflow/.local/lib/python3.7/site-packages/pyspark/context.py", line 195, in __init__
    SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
  File "/home/airflow/.local/lib/python3.7/site-packages/pyspark/context.py", line 417, in _ensure_initialized
    SparkContext._gateway = gateway or launch_gateway(conf)
  File "/home/airflow/.local/lib/python3.7/site-packages/pyspark/java_gateway.py", line 96, in launch_gateway
    proc = Popen(command, **popen_kwargs)
  File "/usr/local/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/usr/local/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/spark/./bin/spark-submit': '/opt/spark/./bin/spark-submit'
[2022-06-20 23:25:11,279] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=tutorial_request, task_id=ola, execution_date=20220620T232507, start_date=20220620T232511, end_date=20220620T232511
[2022-06-20 23:25:11,300] {standard_task_runner.py:97} ERROR - Failed to execute job 100 for task ola ([Errno 2] No such file or directory: '/opt/spark/./bin/spark-submit': '/opt/spark/./bin/spark-submit'; 84)
[2022-06-20 23:25:11,366] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-06-20 23:25:11,415] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
