[2022-06-20 23:20:56,737] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: tutorial_request.ola manual__2022-06-20T23:20:54.294376+00:00 [queued]>
[2022-06-20 23:20:56,743] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: tutorial_request.ola manual__2022-06-20T23:20:54.294376+00:00 [queued]>
[2022-06-20 23:20:56,744] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-20 23:20:56,745] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-06-20 23:20:56,746] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-20 23:20:56,757] {taskinstance.py:1377} INFO - Executing <Task(Ola): ola> on 2022-06-20 23:20:54.294376+00:00
[2022-06-20 23:20:56,761] {standard_task_runner.py:52} INFO - Started process 126 to run task
[2022-06-20 23:20:56,764] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'tutorial_request', 'ola', 'manual__2022-06-20T23:20:54.294376+00:00', '--job-id', '95', '--raw', '--subdir', 'DAGS_FOLDER/hello.py', '--cfg-path', '/tmp/tmp_rbtgl02', '--error-file', '/tmp/tmpvdv7ftp2']
[2022-06-20 23:20:56,765] {standard_task_runner.py:80} INFO - Job 95: Subtask ola
[2022-06-20 23:20:56,818] {task_command.py:370} INFO - Running <TaskInstance: tutorial_request.ola manual__2022-06-20T23:20:54.294376+00:00 [running]> on host 2672e68a2d5a
[2022-06-20 23:20:56,871] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@example.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=tutorial_request
AIRFLOW_CTX_TASK_ID=ola
AIRFLOW_CTX_EXECUTION_DATE=2022-06-20T23:20:54.294376+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-20T23:20:54.294376+00:00
[2022-06-20 23:20:56,900] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/dags/operators/silver/silver.py", line 11, in execute
    spark = SparkSession.builder.master("local[*]").getOrCreate()
  File "/home/airflow/.local/lib/python3.7/site-packages/pyspark/sql/session.py", line 269, in getOrCreate
    sc = SparkContext.getOrCreate(sparkConf)
  File "/home/airflow/.local/lib/python3.7/site-packages/pyspark/context.py", line 483, in getOrCreate
    SparkContext(conf=conf or SparkConf())
  File "/home/airflow/.local/lib/python3.7/site-packages/pyspark/context.py", line 195, in __init__
    SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
  File "/home/airflow/.local/lib/python3.7/site-packages/pyspark/context.py", line 417, in _ensure_initialized
    SparkContext._gateway = gateway or launch_gateway(conf)
  File "/home/airflow/.local/lib/python3.7/site-packages/pyspark/java_gateway.py", line 96, in launch_gateway
    proc = Popen(command, **popen_kwargs)
  File "/usr/local/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/usr/local/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/spark/./bin/spark-submit': '/opt/spark/./bin/spark-submit'
[2022-06-20 23:20:56,912] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=tutorial_request, task_id=ola, execution_date=20220620T232054, start_date=20220620T232056, end_date=20220620T232056
[2022-06-20 23:20:56,925] {standard_task_runner.py:97} ERROR - Failed to execute job 95 for task ola ([Errno 2] No such file or directory: '/opt/spark/./bin/spark-submit': '/opt/spark/./bin/spark-submit'; 126)
[2022-06-20 23:20:56,937] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-06-20 23:20:56,959] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
