[2022-06-20 23:25:57,722] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: tutorial_request.ola manual__2022-06-20T23:20:54.294376+00:00 [queued]>
[2022-06-20 23:25:57,729] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: tutorial_request.ola manual__2022-06-20T23:20:54.294376+00:00 [queued]>
[2022-06-20 23:25:57,731] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-20 23:25:57,732] {taskinstance.py:1357} INFO - Starting attempt 2 of 2
[2022-06-20 23:25:57,733] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-20 23:25:57,742] {taskinstance.py:1377} INFO - Executing <Task(Ola): ola> on 2022-06-20 23:20:54.294376+00:00
[2022-06-20 23:25:57,749] {standard_task_runner.py:52} INFO - Started process 125 to run task
[2022-06-20 23:25:57,753] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'tutorial_request', 'ola', 'manual__2022-06-20T23:20:54.294376+00:00', '--job-id', '101', '--raw', '--subdir', 'DAGS_FOLDER/hello.py', '--cfg-path', '/tmp/tmpzs5x3u15', '--error-file', '/tmp/tmpmvlqp0xp']
[2022-06-20 23:25:57,754] {standard_task_runner.py:80} INFO - Job 101: Subtask ola
[2022-06-20 23:25:57,809] {task_command.py:370} INFO - Running <TaskInstance: tutorial_request.ola manual__2022-06-20T23:20:54.294376+00:00 [running]> on host e1cc88e9e73c
[2022-06-20 23:25:57,858] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@example.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=tutorial_request
AIRFLOW_CTX_TASK_ID=ola
AIRFLOW_CTX_EXECUTION_DATE=2022-06-20T23:20:54.294376+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-20T23:20:54.294376+00:00
[2022-06-20 23:25:57,883] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/dags/operators/silver/silver.py", line 11, in execute
    spark = SparkSession.builder.master("local[*]").getOrCreate()
  File "/home/airflow/.local/lib/python3.7/site-packages/pyspark/sql/session.py", line 269, in getOrCreate
    sc = SparkContext.getOrCreate(sparkConf)
  File "/home/airflow/.local/lib/python3.7/site-packages/pyspark/context.py", line 483, in getOrCreate
    SparkContext(conf=conf or SparkConf())
  File "/home/airflow/.local/lib/python3.7/site-packages/pyspark/context.py", line 195, in __init__
    SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
  File "/home/airflow/.local/lib/python3.7/site-packages/pyspark/context.py", line 417, in _ensure_initialized
    SparkContext._gateway = gateway or launch_gateway(conf)
  File "/home/airflow/.local/lib/python3.7/site-packages/pyspark/java_gateway.py", line 96, in launch_gateway
    proc = Popen(command, **popen_kwargs)
  File "/usr/local/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/usr/local/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/spark/./bin/spark-submit': '/opt/spark/./bin/spark-submit'
[2022-06-20 23:25:57,901] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=tutorial_request, task_id=ola, execution_date=20220620T232054, start_date=20220620T232557, end_date=20220620T232557
[2022-06-20 23:25:57,910] {standard_task_runner.py:97} ERROR - Failed to execute job 101 for task ola ([Errno 2] No such file or directory: '/opt/spark/./bin/spark-submit': '/opt/spark/./bin/spark-submit'; 125)
[2022-06-20 23:25:57,925] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-06-20 23:25:57,948] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
