[2022-06-20 22:06:31,040] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: tutorial_request.votation manual__2022-06-20T22:06:26.064090+00:00 [queued]>
[2022-06-20 22:06:31,048] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: tutorial_request.votation manual__2022-06-20T22:06:26.064090+00:00 [queued]>
[2022-06-20 22:06:31,049] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-20 22:06:31,051] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-06-20 22:06:31,052] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-20 22:06:31,061] {taskinstance.py:1377} INFO - Executing <Task(Votation): votation> on 2022-06-20 22:06:26.064090+00:00
[2022-06-20 22:06:31,067] {standard_task_runner.py:52} INFO - Started process 771 to run task
[2022-06-20 22:06:31,070] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'tutorial_request', 'votation', 'manual__2022-06-20T22:06:26.064090+00:00', '--job-id', '81', '--raw', '--subdir', 'DAGS_FOLDER/hello.py', '--cfg-path', '/tmp/tmpkm8su2wt', '--error-file', '/tmp/tmpl4r4d2gk']
[2022-06-20 22:06:31,073] {standard_task_runner.py:80} INFO - Job 81: Subtask votation
[2022-06-20 22:06:31,111] {task_command.py:370} INFO - Running <TaskInstance: tutorial_request.votation manual__2022-06-20T22:06:26.064090+00:00 [running]> on host 4fac23c61f86
[2022-06-20 22:06:31,154] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@example.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=tutorial_request
AIRFLOW_CTX_TASK_ID=votation
AIRFLOW_CTX_EXECUTION_DATE=2022-06-20T22:06:26.064090+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-20T22:06:26.064090+00:00
[2022-06-20 22:06:31,158] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/dags/operators/request/votation_by_senators.py", line 15, in execute
    senators = pd.read_csv("./data/list_senators.csv", sep = ";")
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: './data/list_senators.csv'
[2022-06-20 22:06:31,167] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=tutorial_request, task_id=votation, execution_date=20220620T220626, start_date=20220620T220631, end_date=20220620T220631
[2022-06-20 22:06:31,176] {standard_task_runner.py:97} ERROR - Failed to execute job 81 for task votation ([Errno 2] No such file or directory: './data/list_senators.csv'; 771)
[2022-06-20 22:06:31,202] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-06-20 22:06:31,224] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
